# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://sejutadigitalpreneur.github.io
title: Sejuta Digital Preneur
email: your-email@domain.com
author: Tri Afrizal Hilmi, S.Pd.
description: > # "Write an awesome description for your new site here. 
  Program Mentoring Sejuta Digital Preneur (SDP) dirancang khusus untuk membantu mitra-mitra TreniNet Community lintas jaringan. Memberikan strategy, tools, dan fasilitas pendukung lainnya agar bisnis
  menjadi sistematis, otomatis dan laris.
copyright: 'Copyright &copy; 2019 All Rights Reserved.'
# credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://fb.me/shofwa.paytren
  - title: instagram
    url: https://instagram.com/afzhilmi
  - title: telegram
    url: 
